import lackey
from re_tests_plugin import *

def test_check_comparer_databases(open_connection):
    lackey.click("str_menu_database.png")
    lackey.click("tree_Create_Database.png")
    lackey.click("field_Connection_Name.png")
    lackey.type("test")
    lackey.click("field_Database_File.png")
    lackey.type("C:\Windows\Temp\Test.fdb")
    lackey.click("field_User_Name.png")
    lackey.type("SYSDBA")
    lackey.click("field_Password.png")
    lackey.type("masterkey")
    lackey.click("chb_store_pass.png")
    lackey.click("text_Create.png")
    lackey.click("text_Yes.png")
    lackey.doubleClick("icon_conn.png")
    lackey.click("tools.png")
    lackey.click("comparer.png")
    lackey.click("text_Source.png")
    lackey.type("{DOWN}")
    lackey.type("{ENTER}")
    lackey.click("button_arrows.png")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type(lackey.Key.SPACE)
    lackey.click("button_compare.png")
    time.sleep(2)
    result1 = lackey.exists("text_Objects_to_create.png")
    lackey.click("bt_OK_blue.png")
    result2 = lackey.exists("text_Comparing_Finish_blue.png")
    lackey.click("text_Output.png")
    result3 = lackey.exists("text_SALES_INTEG.png")
    lackey.click("text_View.png")
    lackey.doubleClick("text_To_Create.png")
    result4 = lackey.exists("text_Objects_Domains_Tables.png")
    lackey.doubleClick("text_To_Create.png")
    lackey.click("text_SQL.png")
    result5 = lackey.exists("text_ALTER_TABLE.png")
    lackey.click("icon_cross.png")
    lackey.click("icon_cross.png")
    lackey.click("icon_cross.png")
    lackey.rightClick("text_test_lowercase.png")
    lackey.click("text_Disconnect.png")
    time.sleep(1)
    lackey.rightClick("text_test_lowercase.png")
    lackey.click("tree_remove_test.png")
    lackey.click("bt_yes.png")
    assert result1 != None
    assert result2 != None
    assert result3 != None
    assert result4 != None
    assert result5 != None