import lackey
from re_tests_plugin import *

def test_check_constraints_spacebar(open_connection):
    lackey.click("tree_plus.png")
    lackey.rightClick("icon_tables.png")
    lackey.click("tree_create_menu.png")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("test comment")
    lackey.type("{TAB}")
    lackey.type("b")
    time.sleep(1)
    lackey.type("b")
    lackey.click("bt_OK.png")
    lackey.click("bt_commit.png")
    lackey.click("tree_plus_tables.png")
    lackey.doubleClick("text_NEW_TABLE_1.png")
    lackey.click("tab_constraints.png")
    lackey.click("bt_insert_constraint.png")
    lackey.click("text_PRIMARY.png")
    lackey.click("text_UNIQUE.png")
    lackey.doubleClick("text_TEST_COMMENT_CAPS.png")
    lackey.click("bt_OK.png")
    result1 = lackey.exists("text_constraints_visible.png")
    lackey.click("bt_commit.png")
    result2 = lackey.exists("text_UQ_NEW_TABLE_1_1.png")
    lackey.click("icon_cross.png")
    lackey.rightClick("text_NEW_TABLE_1_blue.png")
    lackey.click("text_Delete_NEW_TABLE_1.png")
    lackey.click("bt_commit.png")
    assert result1 != None
    assert result2 != None