import lackey
from re_tests_plugin import *

def test_check_data_warning(open_connection):
    lackey.click("tree_plus.png")
    lackey.rightClick("icon_tables.png")
    lackey.click("tree_create_menu.png")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("{TAB}")
    lackey.type("test comment")
    lackey.type("{TAB}")
    lackey.type("b")
    time.sleep(1)
    lackey.type("b")
    lackey.click("bt_OK.png")
    lackey.click("bt_commit.png")
    lackey.click("tree_plus_tables.png")
    lackey.doubleClick("text_NEW_TABLE_1.png")
    lackey.click("tab_data.png")
    lackey.click("bt_insert_record.png")
    lackey.click("icon_commit_data.png")
    time.sleep(3)
    lackey.click("text_NULL_blue.png")
    lackey.click("bt_delete_record.png")
    lackey.click("tab_constraints.png")
    lackey.click("text_Yes.png")
    result1 = lackey.exists("text_An_error_visible.png")
    lackey.click("bt_close.png")
    lackey.click("icon_cross.png")
    lackey.rightClick("text_NEW_TABLE_1_blue.png")
    lackey.click("text_Delete_NEW_TABLE_1.png")
    lackey.click("bt_commit.png")
    lackey.click("text_Yes.png")
    result2 = lackey.exists("text_An_error_visible.png")
    lackey.click("bt_close.png")
    assert result1 != None
    assert result2 != None